Added operations for DO_SOMETHING and OFF_WITH.
AnUnknownMiner/FOAAS-Java pull request #9
Opened 2016-11-20 04:17 UTC by einstein29

The corresponding operations are added.

2016-11-23 19:35 UTC, SSederberg requested changes

2016-11-23 19:35 UTC, SSederberg commented on src/me/spencersederberg/jfoaas/JFOAAS.java
> +     * @param behavior - Fuck off with sofa.
Change the param description to "The behavior being told to fuck off" and I'll merge

2016-11-26 09:36 UTC, einstein29 commented
Parameter descirption has been changed accordingly.

2016-11-26 16:41 UTC, SSederberg approved these changes

2016-11-26 16:42 UTC, merged